name: Build and Deploy Stock Alerts

on:
  pull_request:
    branches:
      - main
        
jobs:
  StockTracker build and deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
        
      - name: Restore dependencies
        run: dotnet restore ./src/StockTracker/**/*.csproj
        
      - name: Build project       
        run: dotnet build ./src/StockTracker/**/*.csproj --configuration Release
        
      - name: Test project        
        run: dotnet test ./src/StockTracker/**/*.csproj --configuration Release
        
      - name: Publish project
        run: dotnet publish ./src/StockTracker/**/*.csproj --configuration Release --output ./publish/StockTracker
        
  TradeStream build and deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore ./src/TradeStream/**/*.csproj
        
      - name: Build project
        run: dotnet build ./src/TradeStream/**/*.csproj --configuration Release
        
      - name: Test project
        run: dotnet test ./src/TradeStream/**/*.csproj --configuration Release
        
      - name: Publish project
        run: dotnet publish ./src/TradeStream/**/*.csproj --configuration Release --output ./publish/TradeStream
        
  Webhook build and deploy:
    - uses: actions/checkout@main

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/Webhook/WebhookSendAlerts.Console/*.csproj
      
    - name: Build project
      run: dotnet build ./src/Webhook/WebhookSendAlerts.Console/*.csproj --configuration Release
      
    - name: Test project
      run: dotnet test ./src/Webhook/WebhookSendAlerts.Console/*.csproj --configuration Release
      
    - name: Publish project
      run: dotnet publish ./src/Webhook/WebhookSendAlerts.Console/*.csproj --configuration Release --output ./publish/Webhook
    
        


